# Generated by Django 3.0.6 on 2020-07-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('weather', models.TextField()),
                ('description', models.TextField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('visibility', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
